trigger:
- main

pool:
  name: default

steps:

- script: |
    wget https://github.com/bazelbuild/bazel/releases/download/7.6.1/bazel-7.6.1-installer-linux-x86_64.sh
    chmod +x bazel-7.6.1-installer-linux-x86_64.sh
    ./bazel-7.6.1-installer-linux-x86_64.sh --user
    echo "##vso[task.prependpath]$HOME/bin"
  displayName: 'Install Bazel'

- script: bazel build //cc_binary:smart_pointer
  displayName: 'Build Bazel Target: smart_pointer'

- script: bazel build //cc_binary:static_vector
  displayName: 'Build Bazel Target: static_vector'

- task: Bash@3
  displayName: 'Check smart_pointer build results'
  inputs:
    targetType: 'inline'
    script: |
      SP_BINARY=$(bazel cquery //cc_binary:smart_pointer --output=files)
      echo "##vso[task.setvariable variable=SPBinary;]$SP_BINARY"

- script: |
    SV_BINARY=$(bazel cquery //cc_binary:static_vector --output=files)
    echo "##vso[task.setvariable variable=SVBinary;]$SV_BINARY"
  displayName: 'Check static_vector build results'

- publish: $(System.DefaultWorkingDirectory)/$(SPBinary)
  displayName: 'Publish SP binary'
  artifact: sp_binary

- publish: $(System.DefaultWorkingDirectory)/$(SVBinary)
  displayName: 'Publish SV binary'
  artifact: sv_binary
