# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: |
    wget https://github.com/bazelbuild/bazel/releases/download/7.6.1/bazel-7.6.1-installer-linux-x86_64.sh
    chmod +x bazel-7.6.1-installer-linux-x86_64.sh
    ./bazel-7.6.1-installer-linux-x86_64.sh --user
    echo "##vso[task.prependpath]$HOME/bin"
  displayName: 'Install Bazel'

- script: bazel build //expand_template:hello_world_template
  displayName: 'Build Bazel Target: hello_world_template'

- script: |
    bazel cquery //expand_template:hello_world_template --output=files
    ls -al bazel-out/expand_template
  displayName: 'Run a multi-line script'
