cc_binary(
    name = "01_bazel/shared_pointer",
    srcs = [
        "01_bazel/shared_pointer/main.cpp",
        "01_bazel/shared_pointer/shared_pointer.h",
    ],
)

cc_binary(
    name = "01_bazel/static_vector",
    srcs = [
        "01_bazel/static_vector/main.cpp",
        "01_bazel/static_vector/static_vector.h",
    ],
    copts = ["-std=c++17"],
)
