cc_binary(
    name = "smart_pointer",
    srcs = [
        "smart_pointer/main.cpp",
        "smart_pointer/smart_pointer.h",
    ],
)

cc_binary(
    name = "static_vector",
    srcs = [
        "static_vector/main.cpp",
        "static_vector/static_vector.h",
    ],
    copts = ["-std=c++17"],
)
